platform :ios, '12.0'

target 'Mosaico' do
  use_frameworks!

  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftyBeaver'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'GLTFSceneKit', :git => 'https://github.com/Jordan-Campbell/GLTFSceneKit.git', :branch => 'shaders'
  pod 'Zip', '~> 1.1'

end
